# action.yaml
name: 'gh-check-pr-is-updated'
description: 'GitHub Actions check if PRs branch is updated'
author: 'Ivan Ogasawara'
inputs:
  remote_branch:
    description: 'Remote branch (e.g.: upstream/main)'
    required: true
  pr_sha:
    description: 'PR SHA'
    required: true

branding:
  icon: check-circle
  color: green

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.remote_branch }}
    - ${{ inputs.pr_sha }}
