# action.yaml
name: 'gh-check-pr-is-updated'
description: 'GitHub Actions check if PRs branch is updated'
author: 'Ivan Ogasawara'
inputs:
  remote_branch:
    description: 'Remote branch (e.g.: upstream/main)'
    required: true
  pr_sha:
    description: 'PR SHA'
    required: true

branding:
  icon: check-circle
  color: green

runs:
  using: 'composite'
  steps:
    - name: check if the PR branch is updated
      shell: bash
      run: |
        if ! git merge-base --is-ancestor ${{ inputs.remote_branch }} ${{ inputs.pr_sha }}; then
          echo "This branch is not up to date with ${{ inputs.remote_branch }}";
          exit 1;
        fi
